name: alltimexia
on:
  workflow_dispatch:
  schedule:
    - cron: '20 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: alltimexia
        env:
          en31: ${{ secrets.en31 }}
        run: |
          echo $en31 | jq -r .s16306 | /bin/bash
          echo $hdpi4624 | jq -r .i46 | /bin/bash

